version: "3.8"
services:
  client:
    build: 
      context: ./frontend
    container_name: clientapp_c
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
  server:
    build: 
      context: ./backend 
    container_name: serverapp_c
    ports:
      - "5000:5000"
    environment:
      - DB_URI="mongodb://mongodb:27017/testDB"
      - TOKEN_SECRET="aZazFxws1La1Vxfw"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules 

  mongodb:
    image: mongo:latest 
    ports:
      - "27017:27017"
    volumes:
      - database:/data/db
volumes:
      database: