@startuml "Crowdfunding Platform" usecase diagram
left to right direction
skinparam packageStyle rectangle

actor Backer 
actor Campaign_Owner
actor Administrator

package "Crowdfunding Platform" {

usecase "Create Campaign" as UC1
usecase "Fund Campaign" as UC2
usecase "Manage Campaign" as UC3
usecase "Fulfill Rewards" as UC4
usecase "View Campaigns" as UC5
usecase "Analytics" as UC7
usecase "Manage Users" as UC8
usecase "Manage Categories" as UC9
usecase "Authentification" as UC11

UC1 ..> UC11 : <<include>>
UC2 ..> UC11 : <<include>>
UC3 ..> UC11 : <<include>>
UC4 ..> UC11 : <<include>>
UC7 ..> UC11 : <<include>>
UC8 ..> UC11 : <<include>>
UC9 ..> UC11 : <<include>>

Campaign_Owner --|>  Backer

Administrator --|>  Campaign_Owner

Backer .. UC5
Backer .. UC2
Campaign_Owner .. UC1
Campaign_Owner .. UC3
Campaign_Owner .. UC4
Campaign_Owner .. UC7
Administrator .. UC8
Administrator .. UC9

}

@enduml